services:
  # PostgreSQL 데이터베이스
  db:
    container_name: db
    image: postgres:16
    restart: always
    env_file:
      - env/.env.development
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "kim-yeon-woo" -d sunnydb']
      interval: 5s
      timeout: 5s
      retries: 10

  # Django 개발 서버
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: >
      sh -c "python manage.py migrate --settings=configs.settings.development
      && python manage.py runserver 0.0.0.0:8000 --settings=configs.settings.development"
    env_file:
      - env/.env.development
    environment:
      DJANGO_SETTINGS_MODULE: configs.settings.development
      PYTHONPATH: /app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
